// <auto-generated />
using System;
using ClinicaApiCore.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClinicaApiCore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230913105848_PacientesTab")]
    partial class PacientesTab
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClinicaApiCore.Entities.Medicos", b =>
                {
                    b.Property<long>("ID_MEDICO_LONG")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID_MEDICO_LONG"));

                    b.Property<string>("CPF_STR")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("NOME_STR")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NUM_REGISTRO_STR")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID_MEDICO_LONG");

                    b.ToTable("MEDICOS_TAB");
                });

            modelBuilder.Entity("ClinicaApiCore.Entities.Pacientes", b =>
                {
                    b.Property<long>("ID_PACIENTE_LONG")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID_PACIENTE_LONG"));

                    b.Property<string>("CELULAR_STR")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CPF_STR")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("NOME_STR")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("ID_PACIENTE_LONG");

                    b.ToTable("PACIENTES_TAB");
                });

            modelBuilder.Entity("ClinicaApiCore.Entities.Procedimentos", b =>
                {
                    b.Property<long>("ID_PROCEDIMENTO_LONG")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID_PROCEDIMENTO_LONG"));

                    b.Property<string>("DESCRICAO_STR")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal?>("VALOR_DEC")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID_PROCEDIMENTO_LONG");

                    b.ToTable("PROCEDIMENTOS_TAB");
                });
#pragma warning restore 612, 618
        }
    }
}
